Frontend insight page linking
GDSCUTM-CommunityProjects/UTimeManager pull request #38
Opened 2022-04-24 22:46 UTC by KarandeepLubana

Completed in this PR:

- link insight ui page to the api

2022-04-24 23:30 UTC, hiimchrislim commented on client/src/components/TaskDurationBarChart/TaskDurationBarChart.js
> +        barCategoryGap={1000}
Is this still needed? (i.e. If removed, will this change anything with the way the chart renders?)

2022-04-24 23:31 UTC, hiimchrislim commented on client/src/components/TaskDurationBarChart/TaskDurationBarChart.js
> +        if (taskDifference.percentDifference > 100) {
General Note: Might need to remove this? But it's okay for now

2022-04-24 23:33 UTC, hiimchrislim requested changes
Looks pretty good! I just left a minor few comments to take a look at. If you have any questions, please let me know

2022-04-24 23:33 UTC, hiimchrislim commented
Also you should merge the current version of develop into this branch such that we resolve any conflict issues.

2022-04-25 20:38 UTC, V-X-L-U commented on client/src/components/TaskDurationBarChart/TaskDurationBarChart.js
> +        barCategoryGap={1000}
Karandeep: Removed.

2022-04-25 20:40 UTC, V-X-L-U commented
> Also you should merge the current version of develop into this branch such that we resolve any conflict issues.

Merged and resolved conflicts. I'll be helping with this branch while Karandeep is working on making the task reflection fetch.

2022-04-26 02:47 UTC, hiimchrislim approved these changes
Looks good! Great work!

2022-04-26 02:47 UTC, merged